name: Promptflow CI
on:
  # Triggers the Promptflow CI on pull request targeting the main branch
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - examples/**
  pull_request_target:
    branches:
      - main
    paths:
      - assets/promptflow/models/**
      - .github/workflows/promptflow-ci.yml
      - scripts/promptflow-ci/**

jobs:
  check-execution-context:
    uses: Azure/azureml-assets/.github/workflows/check-execution-context.yaml@main

  run_promptflow_ci_job:
    runs-on: ubuntu-latest
    needs: check-execution-context
    name: Flow tests
    environment: Testing
    timeout-minutes: 60

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Azure login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
