# This is a basic workflow to help you get started with Actions

name: CI on specific folder change

# Controls when the workflow will run
on:
  push:
    branches:
      - main
    paths:
      - 'test/**'
      - '!test/a.*'
      - '!test/b/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:  
  continuous_delivery_release:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    name: Continuous delivery release
    steps:
      - name: echo hello
        run: echo "hello"
