name: Get PR from push

on:
  push

jobs:
  test_step:
    runs-on: ubuntu-latest
    name: test
    
    steps:
      - name: Override version with PR number
        if: github.event_name == 'push'
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }}
        run: gh pr view --json number -q .number
        
