name: Get PR from push

on:
  push:
    branches:
      - main

jobs:
  test_step:
    runs-on: ubuntu-latest
    name: test
    
    steps:
      - name: Override version with PR number
        if: github.event_name == 'push'
        run:
          echo "${{ github.event.push.push_id }}"
            
        
