name: Get PR from push

on:
  push:
    branches:
      - main

jobs:
  test_step:
    runs-on: ubuntu-latest
    name: test
    
    steps:
      - name: Override version with PR number
        id: findPr
        if: github.event_name == 'push'
        uses: jwalton/gh-find-current-pr@v1.3.2
        with:
          state: all
      - name: Override version with PR number
        if: github.event_name == 'push' && steps.findPR.outputs.pr
        env:
          PR: ${{ steps.findPr.outputs.pr }}
        run:
          echo "${PR}"
            
        
