name: Get PR from push

on:
  push:
    branches:
      - main

jobs:
  test_step:
    runs-on: ubuntu-latest
    name: test
    
    steps:
      - name: Override version with PR number
        if: github.event_name == 'push'
        run:
          echo "${{ github.run_id }}"
          echo "${{ github.event.push.head }}"
          echo "${{ github.event.pushevent.head }}"
          echo "${{ github.event.pull_request.number }}"


            
        
