name: Update target branch from main

on:
  workflow_dispatch:
    inputs:
      targetBranch:
        description: 'Target branch'     
        required: true
        default: 'test'
      mergeTag:
        description: 'Merge tag or not, default is merge main branch'
        required: true
        type: boolean
        default: false
      tagName:
        description: 'Tag name to merge'
        required: true
        default: 'dummy_tag'
concurrency: ${{ github.workflow }}

env:
  main_branch: main
  release_branch: ${{ github.event.inputs.targetBranch }}
  tagName:  ${{ github.event.inputs.tagName }}
  
permissions:
  # Required to clone repo and push commits
  contents: write

jobs:
  update_release_branch:
    name: Update release branch
    if: "github.ref == 'refs/heads/main'"
    runs-on: ubuntu-latest

    steps:
      - name: Clone main branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
 
      - name: Merge main branch to ${{ env.release_branch }}
        if: ${{ github.event.inputs.mergeTag == 'false' }}
        env:
          GIT_AUTHOR_NAME: github-actions[bot]
          GIT_COMMITTER_NAME: GitHub
          GIT_COMMITTER_EMAIL: noreply@github.com
        run: |
          echo "main branch fecth origin"
          git switch main
          git fetch origin

          echo "switch to ${{ env.release_branch }} branch"
          git switch ${{ env.release_branch }}
          git pull

          echo "${{ env.release_branch }} branch merge main branch"
          git merge origin/main
          git push origin ${{ env.release_branch }}

      - name: Merge main branch with tag
        if: ${{ github.event.inputs.mergeTag == 'true' }}
        env:
          GIT_AUTHOR_NAME: github-actions[bot]
          GIT_COMMITTER_NAME: GitHub
          GIT_COMMITTER_EMAIL: noreply@github.com
        run: |
          echo "main branch fecth origin"
          git switch main
          git fetch origin
          git fetch --tags origin

          echo "switch to ${{ env.release_branch }} branch"
          git switch ${{ env.release_branch }}
          git pull

          echo "${{ env.release_branch }} branch merge main branch with tag ${{ env.tagName }}"
          git merge ${{ env.tagName }}
          git push origin ${{ env.release_branch }}
